version: '3.8'

services:
  mariadb:
    image: mariadb:11.4
    container_name: my-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
      MARIADB_DATABASE: mydb
      MARIADB_USER: myusername
      MARIADB_PASSWORD: mypassword
    ports:
      - "3307:3307"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
