spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/mydb
    username: myusername
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # (??) ?? ?? ??
  server:
    port: 8080
